# Generated by Django 5.1 on 2025-04-07 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('account_number', models.CharField(default='0.00', max_length=200, null=True)),
                ('account_name', models.CharField(default='0.00', max_length=200)),
                ('bank_name', models.CharField(default='0.00', max_length=200)),
                ('swift_code', models.CharField(default='0.00', max_length=200)),
                ('bitcoin_address', models.CharField(default='0.00', max_length=200, null=True)),
                ('ethereum_address', models.CharField(default='0.00', max_length=200)),
                ('cashapp_tag', models.CharField(default='0.00', max_length=200)),
                ('paypal_email', models.CharField(default='0.00', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('capital_balance', models.CharField(default='0.00', max_length=200)),
                ('btc', models.CharField(default='0.00', max_length=200, null=True)),
                ('usd', models.CharField(default='0.00', max_length=200)),
                ('bonus_usd', models.CharField(default='0.00', max_length=200)),
                ('plan', models.CharField(default='Silver', max_length=200)),
                ('verify', models.CharField(default='Unverified', max_length=200)),
                ('currency', models.CharField(default='$', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('pin', models.CharField(default='0000', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='avater.png', null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('Report', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(default='1', max_length=200)),
                ('tf_type', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactionone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(default='2', max_length=200)),
                ('tf_type', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(default='4', max_length=200)),
                ('tf_type', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactiontwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(default='3', max_length=200)),
                ('tf_type', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('btc', models.CharField(default='4', max_length=200)),
                ('eth', models.CharField(default='-', max_length=200)),
                ('usdt', models.CharField(default='-', max_length=200)),
                ('usdc', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
